# Generated by Django 3.0.6 on 2020-11-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.IntegerField(verbose_name='Номер аудитории')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=50, verbose_name='Название лекции')),
                ('speaker_name', models.CharField(max_length=50, verbose_name='Имя спикера')),
                ('start_time', models.DateTimeField(verbose_name='Время начала доклада')),
                ('end_time', models.DateTimeField(verbose_name='Время конца доклада')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiences.Audience')),
            ],
        ),
    ]
