# Generated by Django 3.0.6 on 2020-11-10 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20201110_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='audience',
        ),
        migrations.AddField(
            model_name='lecture',
            name='audience_number',
            field=models.IntegerField(default=0, verbose_name='Номер аудитории'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 13, 28, 29, 838343, tzinfo=utc), verbose_name='Время конца доклада'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 13, 28, 29, 838343, tzinfo=utc), verbose_name='Время начала доклада'),
        ),
        migrations.DeleteModel(
            name='Audience',
        ),
    ]
