# Generated by Django 3.0.6 on 2020-11-12 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20201111_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 10, 43, 50, 98250, tzinfo=utc), verbose_name='Время конца доклада'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 10, 43, 50, 98250, tzinfo=utc), verbose_name='Время начала доклада'),
        ),
    ]
