# Generated by Django 3.0.6 on 2020-12-22 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_auto_20201112_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(default='', max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 6, 40, 57, 36386, tzinfo=utc), verbose_name='Время конца доклада'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 6, 40, 57, 36386, tzinfo=utc), verbose_name='Время начала доклада'),
        ),
    ]
