# Generated by Django 3.0.6 on 2020-12-22 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_auto_20201222_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.IntegerField(default=0, verbose_name='Номер аудитории')),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 6, 43, 3, 891755, tzinfo=utc), verbose_name='Время конца доклада'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 6, 43, 3, 891755, tzinfo=utc), verbose_name='Время начала доклада'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='audience_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.Audience'),
        ),
    ]
